version: 2.1

jobs:
  build:
    working_directory: ~/openreview-expertise
    docker:
      - image: ubuntu:18.04
      - image: circleci/redis:6.0.0
    environment:
      PYTHON_VERSION: 3.7
    steps:
      - checkout
      - run:
          name: Setup Miniconda
          command: |
            apt update
            apt install -y wget
            apt install -y make gcc
            apt install -y build-essential
            apt install -y git
            cd $HOME
            wget "https://repo.anaconda.com/miniconda/Miniconda3-4.7.10-Linux-x86_64.sh" -O miniconda.sh
            printf '%s' "8a324adcc9eaf1c09e22a992bb6234d91a94146840ee6b11c114ecadafc68121  miniconda.sh" | sha256sum -c
            bash miniconda.sh -b -p $HOME/miniconda
      - run:
          name: Setup environment
          command: |
            export PATH="$HOME/miniconda/bin:$PATH"
            conda update -y conda
            conda create -n expertise python=$PYTHON_VERSION -c conda-forge
            source ~/miniconda/etc/profile.d/conda.sh
            conda activate expertise
            python --version
            mkdir ~/expertise-utils
            cd ~/expertise-utils
            git clone https://github.com/allenai/specter.git
            cd specter
            wget https://ai2-s2-research-public.s3-us-west-2.amazonaws.com/specter/archive.tar.gz
            tar -xzvf archive.tar.gz
            conda install pytorch cudatoolkit=10.1 -c pytorch 
            pip install -r requirements.txt
            python setup.py install
            conda install -y filelock
            cd ..
            wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1_mWkQ1dr_Vl121WZkbNyNMV3G_bmoQ6s' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1_mWkQ1dr_Vl121WZkbNyNMV3G_bmoQ6s" -O mfr.tar.gz && rm -rf /tmp/cookies.txt
            tar -xzvf mfr.tar.gz
            mv ./mfr/multifacet_recommender_data .
            mv ./multifacet_recommender_data ./multifacet_recommender
            cd ~/openreview-expertise
            pip install -e .
            conda install -y intel-openmp==2019.4
            conda install -y faiss-cpu -c pytorch
      - run:
          name: Run tests
          command: |
            source ~/miniconda/etc/profile.d/conda.sh
            conda activate expertise
            cd ~/openreview-expertise
            mkdir reports
            mkdir reports/pytest
            python -m pytest -s tests --junitxml=reports/pytest/pytest-report.xml --ignore=expertise
      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports
