# This workflow deploys the master branch to the live site

name: prod-deployment

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Authenticate with Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/997553930042/locations/global/workloadIdentityPools/github-identity-pool/providers/github-identity-provider
          service_account: github-actions@sunlit-realm-131518.iam.gserviceaccount.com
          create_credentials_file: true
          cleanup_credentials: true
          export_environment_variables: true
      - name: Configure gcloud
        run: gcloud config set compute/zone us-central1-c
      - name: Run deploy script
        run: |
          gcloud compute ssh openreview@instance-matching-server-gpu --command '/bin/expertise_build.sh' --quiet
