# This workflow deploys the master brance to the dev site

name: dev-deployment

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: false
        default: 'master'
      py_branch:
        description: 'openreview-py branch to deploy'
        required: false
        default: 'master'
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [ master ]
jobs:
  deploy:
    # Allow the job to fetch a GitHub ID token
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add SSH key
        run: |
          mkdir -p /home/runner/.ssh
          echo "${{ secrets.GCLOUD_SSH_KEY }}" > /home/runner/.ssh/google_compute_engine
          echo "${{ secrets.GCLOUD_SSH_KEY_PUB }}" > /home/runner/.ssh/google_compute_engine.pub
          chmod 600 /home/runner/.ssh/google_compute_engine
          chmod 600 /home/runner/.ssh/google_compute_engine.pub
      - name: Authenticate with Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/997553930042/locations/global/workloadIdentityPools/github-identity-pool/providers/github-identity-provider
          service_account: github-actions@sunlit-realm-131518.iam.gserviceaccount.com
          create_credentials_file: true
          cleanup_credentials: true
          export_environment_variables: true
      - name: Configure gcloud
        run: gcloud config set compute/zone us-central1-c
      - name: Run deploy script
        run: |
          gcloud compute ssh openreview@instance-matching-server --command '/bin/expertise_build_dev.sh -b ${{ github.event.inputs.branch }} -p ${{ github.event.inputs.py_branch }}' --quiet
